results = [{"name": "Uma Stone", "maths": 20, "english": 29, "chem": 36, "kis": 19, "geo": 70},
           {"name": "Raymond Chan", "maths": 49, "english": 87, "chem": 39, "kis": 75, "geo": 60},
           {"name": "Mannix Morrison", "maths": 13, "english": 48, "chem": 68, "kis": 55, "geo": 42},
           {"name": "Wang Cooper", "maths": 78, "english": 20, "chem": 57, "kis": 50, "geo": 65},
           {"name": "Marah Blackburn", "maths": 32, "english": 66, "chem": 26, "kis": 53, "geo": 69},
           {"name": "Dacey O'donnell", "maths": 48, "english": 41, "chem": 22, "kis": 59, "geo": 57},
           {"name": "Yoshio Hernandez", "maths": 27, "english": 72, "chem": 38, "kis": 23, "geo": 40},
           {"name": "Merritt Mayer", "maths": 80, "english": 73, "chem": 56, "kis": 31, "geo": 41},
           {"name": "Risa Allen", "maths": 14, "english": 22, "chem": 51, "kis": 82, "geo": 28},
           {"name": "Acton Aguilar", "maths": 53, "english": 67, "chem": 68, "kis": 76, "geo": 20},
           {"name": "Zachary Chan", "maths": 33, "english": 63, "chem": 69, "kis": 17, "geo": 74},
           {"name": "Hu Gordon", "maths": 47, "english": 36, "chem": 58, "kis": 64, "geo": 33},
           {"name": "Xyla Dejesus", "maths": 31, "english": 33, "chem": 63, "kis": 76, "geo": 15},
           {"name": "Bryar Kim", "maths": 36, "english": 57, "chem": 70, "kis": 33, "geo": 15},
           {"name": "Trevor Pugh", "maths": 25, "english": 81, "chem": 53, "kis": 44, "geo": 43},
           {"name": "Steven Sargent", "maths": 72, "english": 79, "chem": 30, "kis": 26, "geo": 36},
           {"name": "Buffy Young", "maths": 40, "english": 76, "chem": 23, "kis": 18, "geo": 67},
           {"name": "Asher Townsend", "maths": 56, "english": 65, "chem": 65, "kis": 81, "geo": 44},
           {"name": "Thor Kane", "maths": 15, "english": 28, "chem": 44, "kis": 81, "geo": 30},
           {"name": "Solomon Gomez", "maths": 15, "english": 46, "chem": 25, "kis": 68, "geo": 46},
           {"name": "Dacey Leblanc", "maths": 78, "english": 65, "chem": 19, "kis": 58, "geo": 40},
           {"name": "Logan Wilcox", "maths": 13, "english": 77, "chem": 56, "kis": 82, "geo": 22},
           {"name": "Hamish Michael", "maths": 78, "english": 83, "chem": 21, "kis": 44, "geo": 19},
           {"name": "Juliet Sims", "maths": 12, "english": 34, "chem": 65, "kis": 89, "geo": 53},
           {"name": "Jarrod Hardin", "maths": 28, "english": 14, "chem": 55, "kis": 47, "geo": 48},
           {"name": "Jacob Gilliam", "maths": 40, "english": 45, "chem": 12, "kis": 13, "geo": 46},
           {"name": "Germane Bass", "maths": 60, "english": 79, "chem": 22, "kis": 37, "geo": 82},
           {"name": "Judith Campbell", "maths": 40, "english": 27, "chem": 20, "kis": 50, "geo": 45},
           {"name": "Julian Sargent", "maths": 64, "english": 85, "chem": 58, "kis": 61, "geo": 59},
           {"name": "Ryder Kelly", "maths": 14, "english": 53, "chem": 51, "kis": 35, "geo": 49},
           {"name": "Ignatius Banks", "maths": 70, "english": 33, "chem": 64, "kis": 57, "geo": 11},
           {"name": "MacKensie Adkins", "maths": 52, "english": 56, "chem": 13, "kis": 24, "geo": 36},
           {"name": "Damon Stark", "maths": 64, "english": 68, "chem": 62, "kis": 29, "geo": 64},
           {"name": "Doris Head", "maths": 75, "english": 28, "chem": 32, "kis": 62, "geo": 46},
           {"name": "Kameko Hall", "maths": 47, "english": 62, "chem": 21, "kis": 78, "geo": 67},
           {"name": "Zeus Sanford", "maths": 67, "english": 14, "chem": 10, "kis": 89, "geo": 57},
           {"name": "Raya Huff", "maths": 62, "english": 82, "chem": 10, "kis": 88, "geo": 72},
           {"name": "Alec Branch", "maths": 70, "english": 87, "chem": 53, "kis": 35, "geo": 88},
           {"name": "Tobias Barrera", "maths": 45, "english": 69, "chem": 55, "kis": 62, "geo": 63},
           {"name": "Carson Rollins", "maths": 18, "english": 20, "chem": 69, "kis": 78, "geo": 41},
           {"name": "Dennis Baldwin", "maths": 45, "english": 33, "chem": 66, "kis": 29, "geo": 12},
           {"name": "Rebecca Singleton", "maths": 52, "english": 75, "chem": 15, "kis": 29, "geo": 15},
           {"name": "Chiquita Farrell", "maths": 45, "english": 67, "chem": 33, "kis": 26, "geo": 35},
           {"name": "Charity Beach", "maths": 73, "english": 83, "chem": 39, "kis": 30, "geo": 38},
           {"name": "Jamal Robbins", "maths": 47, "english": 73, "chem": 41, "kis": 27, "geo": 90},
           {"name": "Olympia Welch", "maths": 77, "english": 44, "chem": 39, "kis": 64, "geo": 13},
           {"name": "Colin Duran", "maths": 37, "english": 41, "chem": 63, "kis": 89, "geo": 51},
           {"name": "Kylan Campos", "maths": 72, "english": 53, "chem": 58, "kis": 61, "geo": 31},
           {"name": "Josephine Moses", "maths": 24, "english": 53, "chem": 16, "kis": 61, "geo": 79},
           {"name": "Xaviera Hanson", "maths": 64, "english": 64, "chem": 47, "kis": 73, "geo": 72},
           {"name": "Maggy Hayes", "maths": 61, "english": 23, "chem": 59, "kis": 26, "geo": 39},
           {"name": "Molly Galloway", "maths": 31, "english": 76, "chem": 53, "kis": 51, "geo": 89},
           {"name": "Xanthus Richmond", "maths": 22, "english": 65, "chem": 32, "kis": 87, "geo": 59},
           {"name": "Nichole Bryant", "maths": 41, "english": 56, "chem": 26, "kis": 76, "geo": 19},
           {"name": "Hu Witt", "maths": 19, "english": 36, "chem": 50, "kis": 16, "geo": 72},
           {"name": "Penelope Coffey", "maths": 55, "english": 69, "chem": 56, "kis": 32, "geo": 81},
           {"name": "Lenore Ashley", "maths": 32, "english": 64, "chem": 42, "kis": 29, "geo": 78},
           {"name": "April Kelly", "maths": 74, "english": 57, "chem": 44, "kis": 76, "geo": 70},
           {"name": "Trevor Frye", "maths": 47, "english": 88, "chem": 53, "kis": 40, "geo": 51},
           {"name": "Dawn Patton", "maths": 61, "english": 26, "chem": 52, "kis": 31, "geo": 81},
           {"name": "Rhona Carney", "maths": 50, "english": 39, "chem": 43, "kis": 50, "geo": 39},
           {"name": "Brian Hampton", "maths": 50, "english": 68, "chem": 23, "kis": 76, "geo": 62},
           {"name": "Zenia Maldonado", "maths": 49, "english": 52, "chem": 21, "kis": 31, "geo": 27},
           {"name": "Cassidy Cabrera", "maths": 62, "english": 75, "chem": 64, "kis": 85, "geo": 42},
           {"name": "Thomas Steele", "maths": 27, "english": 24, "chem": 55, "kis": 79, "geo": 74},
           {"name": "Clayton Boone", "maths": 10, "english": 28, "chem": 19, "kis": 68, "geo": 46},
           {"name": "Rama Ayers", "maths": 13, "english": 73, "chem": 41, "kis": 45, "geo": 66},
           {"name": "Hedy Young", "maths": 34, "english": 29, "chem": 69, "kis": 71, "geo": 39},
           {"name": "Todd Myers", "maths": 72, "english": 34, "chem": 34, "kis": 71, "geo": 89},
           {"name": "Fletcher Giles", "maths": 40, "english": 37, "chem": 49, "kis": 37, "geo": 49},
           {"name": "Norman Curtis", "maths": 52, "english": 45, "chem": 32, "kis": 74, "geo": 24},
           {"name": "Ivan Tate", "maths": 78, "english": 81, "chem": 25, "kis": 11, "geo": 33},
           {"name": "Elmo Avila", "maths": 18, "english": 86, "chem": 40, "kis": 75, "geo": 36},
           {"name": "Logan Barnett", "maths": 25, "english": 32, "chem": 41, "kis": 19, "geo": 54},
           {"name": "Lyle Whitley", "maths": 43, "english": 38, "chem": 44, "kis": 49, "geo": 90},
           {"name": "Dolan Hansen", "maths": 16, "english": 13, "chem": 33, "kis": 56, "geo": 32},
           {"name": "Juliet Hyde", "maths": 43, "english": 66, "chem": 22, "kis": 83, "geo": 71},
           {"name": "Cyrus Lang", "maths": 16, "english": 83, "chem": 43, "kis": 65, "geo": 82},
           {"name": "Kasimir Cervantes", "maths": 71, "english": 37, "chem": 40, "kis": 25, "geo": 58},
           {"name": "Dorothy Whitney", "maths": 35, "english": 23, "chem": 63, "kis": 70, "geo": 65},
           {"name": "Andrew Travis", "maths": 21, "english": 41, "chem": 60, "kis": 75, "geo": 68},
           {"name": "Pamela Dunlap", "maths": 68, "english": 88, "chem": 25, "kis": 81, "geo": 23},
           {"name": "Lillian Pearson", "maths": 23, "english": 19, "chem": 36, "kis": 41, "geo": 14},
           {"name": "Hadassah Rowe", "maths": 45, "english": 45, "chem": 28, "kis": 34, "geo": 21},
           {"name": "Hilel Summers", "maths": 38, "english": 21, "chem": 21, "kis": 82, "geo": 41},
           {"name": "Meredith Hewitt", "maths": 75, "english": 65, "chem": 16, "kis": 33, "geo": 17},
           {"name": "Xyla Brewer", "maths": 58, "english": 47, "chem": 38, "kis": 77, "geo": 67},
           {"name": "John Branch", "maths": 41, "english": 57, "chem": 43, "kis": 83, "geo": 60},
           {"name": "Jocelyn Mayer", "maths": 60, "english": 43, "chem": 10, "kis": 26, "geo": 52},
           {"name": "Kamal Salinas", "maths": 62, "english": 73, "chem": 17, "kis": 11, "geo": 25},
           {"name": "Allen Jordan", "maths": 36, "english": 47, "chem": 57, "kis": 43, "geo": 70},
           {"name": "Gage Montgomery", "maths": 48, "english": 59, "chem": 61, "kis": 57, "geo": 86},
           {"name": "Yoshi French", "maths": 75, "english": 56, "chem": 68, "kis": 76, "geo": 10},
           {"name": "Camilla Richmond", "maths": 40, "english": 86, "chem": 62, "kis": 79, "geo": 36},
           {"name": "Willa Sears", "maths": 58, "english": 72, "chem": 31, "kis": 12, "geo": 30},
           {"name": "Kamal Page", "maths": 58, "english": 33, "chem": 55, "kis": 29, "geo": 41},
           {"name": "Quyn Ewing", "maths": 37, "english": 17, "chem": 65, "kis": 67, "geo": 27},
           {"name": "Geraldine Byrd", "maths": 22, "english": 81, "chem": 58, "kis": 47, "geo": 22},
           {"name": "Wayne Nicholson", "maths": 17, "english": 62, "chem": 63, "kis": 42, "geo": 14},
           {"name": "Hilel Franco", "maths": 78, "english": 73, "chem": 35, "kis": 82, "geo": 14}]

print(len(results))
results.sort(key=lambda res: res['maths'], reverse=True)
print(results[0])

for result in results:
    total= result['maths']+result['english']+result['chem']+result['kis']+result['geo']
    result['total']=total

print(results)
results.sort(key=lambda res: res['total'], reverse=True)
print(results[0])
print(results[-1])

#mean#meadian#top 10students in geo


